### ISSUE TITLE
cant add ammo to anything but pistols 

### ISSUE THREAD

**Issue by wempaii** [Gmod4phun/phunbase#21]

**Comment by Gmod4phun** [comment]
More info would be nice. Also, make sure you don't have too many weapon addon's installed (CW 2.0, FAS 2.0, TFA) because there is a limit on how many ammo types GMod can have.

**Comment by wempaii** [comment]
oh sorry, yeah i have CW2.0 KK INS2 and a lot of TFA addons. Could that be the problem?

**Comment by wempaii** [comment]
and it was. thanks for the help. :)
