### ISSUE TITLE
Ammo Update Error

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [Gmod4phun/phunbase#3]
Ammunition is the same, but when the base is different, there is an error in updating the ammo state. For example, if you shoot a phun-based SMG, reload it, deploy a basic SMG, and deploy a phun-based SMG, you're back to the ammo before reloading. In addition, there is an error that the ammunition status update is one minute slower.(this error also appears on the same weapon base. and, this thread used translator, so maybe it's have context error.)

**Comment by Gmod4phun** [comment]
I am not sure what you are talking about, I don't have any problems regarding ammo

**Comment by RonaldMacdonaldTrump** [comment]
@Gmod4phun I think i'm using old version. thanks for answer my question.
